apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jd5k
  namespace: nmukherj-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2c3aa6a9e48b75c7f5ec467ea89eb222cb16e1ad5552a8b47bc060b22a043733
        name: my-nodejs
        resources: {}
status: {}
