apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jd5k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jd5k
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-jd5k
  namespace: nmukherj-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jd5k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jd5k
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2c3aa6a9e48b75c7f5ec467ea89eb222cb16e1ad5552a8b47bc060b22a043733
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 3003
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
